### ISSUE TITLE
TestFlight expired

### ISSUE THREAD

**Issue by tomchatting** [ashtom/hadge#132]
The Hadge TestFlight release has expired. Can no longer open the app or access its TestFlight link. 

![Screenshot showing beta has expired error](https://github.com/ashtom/hadge/assets/78462/126c9601-b0b9-460f-8d20-17d9a34fa496)

**Comment by ashtom** [comment]
Thanks, just uploaded a new build `1.0 (46)`.

**Comment by tomchatting** [comment]
Build `1.0 (46)` pushed and on device. Thanks!
