### ISSUE TITLE
Unable to Launch App on iOS

### ISSUE THREAD

**Issue by willtheorangeguy** [ashtom/hadge#133]
I am currently in the TestFlight Beta for the app and have it downloaded. When I attempt to launch the app, the message `"Hadge" Beta has expired` appears. 

I cannot update the app through the App Store or TestFlight, so I believe a new build needs to be created and released.

**Comment by ashtom** [comment]
Sorry about that, time is flying. New build is on TestFlight now!

**Comment by willtheorangeguy** [comment]
It's working again! Thanks.
