### ISSUE TITLE
TestFlight can't use.

### ISSUE THREAD

**Issue by uni-pai** [ashtom/hadge#2]
I was removed from hadge's testflight and the link on the home page is no longer accepting new testflights(I opened the link on my iPhone). can I still join testflight?

**Comment by rohithpudari** [comment]
@ashtom, it looks like the beta has expired.

**Comment by ashtom** [comment]
Just uploaded a new build to TestFlight, so things should work again. Sorry about that, will set a reminder in my calendar to avoid expired builds. 😉

**Comment by uni-pai** [comment]
The TestFlight has been updated.
